language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
  exclude:
    - env: SYMFONY_VERSION=dev-master
      php: 5.3
    - env: SYMFONY_VERSION=2.3.*
      php: 5.6
